
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.ButtonActivator;
import project.ColorGenerator;
import project.FormInterface;
import project.InsertUpdateDelete;
import project.Select;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alk_6
 */
public class TaskInsert extends javax.swing.JFrame {

    private static int taskID;    
    private static String dateCreated;
    private static String taskType;
    private static String description;
    private static String importance;
    private static String dateDue;
    private static String dateCompleted;
    private static String inchargeName;
    private static String note;
    private static boolean isActive;
    
    private FormInterface observer;    
    private static TaskInsert instance;
    
    private Color primaryColor = ColorGenerator.generateRandomPrimaryColor();
    private Color secondaryColor = ColorGenerator.generateSecondaryColor(primaryColor);
    private Color thirdColor = ColorGenerator.generateThirdColor(secondaryColor);
    /**
     * Creates new form TaskInsert
     */
    public TaskInsert(int taskID, String dateCreated, String taskType, String description,String importance, String dateDue, String dateCompleted, String inchargeName, String note, boolean isActive) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        jButton5.requestFocusInWindow();
        jButton4.setVisible(false);
        populateTaskTypeComboBox();
        populateImportanceComboBox();
        populateInchargeComboBox();
        
        this.taskID = taskID;
        this.dateCreated = dateCreated;
        this.taskType = taskType;
        this.description = description;
        this.importance = importance;
        this.dateDue = dateDue;
        this.dateCompleted = dateCompleted;
        this.inchargeName = inchargeName;
        this.note = note;
        this.isActive = isActive;
        
        jComboBox2.setSelectedItem(taskType);
        jComboBox3.setSelectedItem(importance);
        jComboBox4.setSelectedItem(inchargeName);
        jCheckBox1.setSelected(isActive);
        
        jTextField11.setText(String.valueOf(taskID));
        jTextField12.setText(description);
        jTextField13.setText(dateCreated);
        jTextField14.setText(dateDue);
        jTextField15.setText(dateCompleted);
        jTextField19.setText(note);
        
        //getRootPane().setDefaultButton(jButton4);        
        ButtonActivator.makeButtonDefaultOnEnter(jButton3);
        ButtonActivator.makeButtonDefaultOnEnter(jButton4);
        ButtonActivator.makeButtonDefaultOnEnter(jButton5);
        
        SimpleDateFormat myFormat= new SimpleDateFormat("yyyy-MM-dd");      
        java.util.Calendar cal=java.util.Calendar.getInstance();
        //jTextField13.setText(myFormat.format(cal.getTime()));
        //jTextField14.setText(myFormat.format(cal.getTime()));
        //jTextField15.setText(myFormat.format(cal.getTime()));
        
        jPanel1.setBackground(primaryColor);
        jPanel4.setBackground(thirdColor);
        jComboBox2.setBackground(thirdColor);
        jComboBox3.setBackground(thirdColor);
        jComboBox4.setBackground(thirdColor);
        jTextField11.setBackground(thirdColor);
        jTextField12.setBackground(thirdColor);
        jTextField13.setBackground(thirdColor);
        jTextField14.setBackground(thirdColor);
        jTextField15.setBackground(thirdColor);
        jTextField19.setBackground(thirdColor);
        jButton5.setBackground(secondaryColor);
        jButton3.setBackground(secondaryColor);
        jButton4.setBackground(secondaryColor);
        jButton6.setBackground(secondaryColor);
        jCheckBox1.setBackground(thirdColor);
    }

    // Setter method for observer
    public void setObserver(FormInterface observer) {
        this.observer = observer;
    }
    
    private void notifyObserver() {
        if (observer != null) {
            observer.updateTask();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField19 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(286, 420));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(242, 16, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("T");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ask");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, -1));

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("/");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 30, 50));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("nsert");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("pdate");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, -1));

        jLabel25.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("U");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 50));

        jLabel26.setFont(new java.awt.Font("Viner Hand ITC", 1, 40)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("I");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("History");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TaskID");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        jTextField11.setBackground(new java.awt.Color(204, 51, 0));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Description");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jTextField12.setBackground(new java.awt.Color(204, 51, 0));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 310, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Type");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 101, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(204, 51, 0));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 120, -1));

        jTextField19.setBackground(new java.awt.Color(204, 51, 0));
        jTextField19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 430, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Note");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 101, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Imp");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(204, 51, 0));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 120, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Incharge");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(204, 51, 0));
        jComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, -1));

        jTextField13.setBackground(new java.awt.Color(204, 51, 0));
        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 150, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Created");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jTextField14.setBackground(new java.awt.Color(204, 51, 0));
        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 150, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Is Active");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Completed");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jTextField15.setBackground(new java.awt.Color(204, 51, 0));
        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 150, -1));

        jCheckBox1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 32, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Due Dt");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Insert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        jButton3.setVisible(true);
        jButton4.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    public String getTaskID() {
        return jTextField11.getText();
    }
     
    public String getTaskType() {
        String selectedTaskType = (String) jComboBox2.getSelectedItem();        
        //int selectedTaskTypeId = nameToIdMap.get(selectedTaskType);
        return selectedTaskType;
    }
        
    public String getImportance() {
        String selectedImportance = (String) jComboBox3.getSelectedItem();        
        //int selectedImportanceId = nameToIdMap.get(selectedImportance);
        return selectedImportance;
    }
    
    public String getIncharge() {
        String selectedInchargeName = (String) jComboBox4.getSelectedItem();        
        //int selectedInchargeId = nameToIdMap.get(selectedInchargeName);
        return selectedInchargeName;
    }
    
    public String getNote() {
        return jTextField19.getText();
    }
    
    public String getDescription() {
        return jTextField12.getText();
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int taskID = Integer.parseInt(jTextField11.getText());
        String dateCreated = jTextField13.getText();
        
        String taskType = (String) jComboBox2.getSelectedItem();        
        int taskTypeID = nameToIdMap.get(taskType);
        
        String description = jTextField12.getText();      
        
        String importance = (String) jComboBox3.getSelectedItem();        
        int importanceID = nameToIdMap.get(importance);
        
        String dateDue = jTextField14.getText();
        String dateCompleted = jTextField15.getText();
        
        String incharge = (String) jComboBox4.getSelectedItem();        
        int inchargeID = nameToIdMap.get(incharge);
        
        String note = jTextField19.getText();
        
        int checkBoxValue;
        if (jCheckBox1.isSelected()) {
    
            checkBoxValue = 1;
        } else {
    
            checkBoxValue = 0;
        }
               
        
        try
        { 
            String query="UPDATE TaskT SET DateCreated = '"+dateCreated+"', TaskTypeID = '"+taskTypeID+"'," +
                        " Description = '"+description+"', ImportanceID = '"+importanceID+"', DateDue = '"+dateDue+"', DateCompleted = '"+dateCompleted+"'," +
                        " InchargeID = '"+inchargeID+"', Note = '"+note+"', IsActive = '"+checkBoxValue+"' WHERE TaskID = '"+taskID+"' ";
            
                InsertUpdateDelete.setData(query, "Data Updated Successfully");   
                
        observer.updateTask();
        jTextField12.requestFocusInWindow();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String dateCreated = jTextField13.getText();
        String dateDue = jTextField14.getText();  
        String dateCompleted = jTextField15.getText();  
        
        String selectedTaskType = (String) jComboBox2.getSelectedItem();        
        int selectedTaskTypeId = nameToIdMap.get(selectedTaskType);
        
        String selectedImportance = (String) jComboBox3.getSelectedItem();        
        int selectedImportanceId = nameToIdMap.get(selectedImportance);
        
        String selectedInchargeName = (String) jComboBox4.getSelectedItem();        
        int selectedInchargeId = nameToIdMap.get(selectedInchargeName);
        
                 
        String note = jTextField19.getText();             
        String description = jTextField12.getText();       
        
        //int profit = Integer.parseInt(jTextField3.getText());
        //ComboItem selectedBrokerItem = (ComboItem) jComboBox1.getSelectedItem();
        //int brokerId = selectedBrokerItem.getValue();

        // Construct the INSERT query
        String query = "INSERT INTO taskt (DateCreated, TaskTypeID, Description, ImportanceID, DateDue, DateCompleted," +
                        " InchargeID, Note, IsActive) VALUES ('"+dateCreated+"', '"+selectedTaskTypeId+"', '"+description+"', '"+selectedImportanceId+"'," +
                        " '"+dateDue+"', '"+dateCompleted+"', '"+selectedInchargeId+"', '"+note+"', '0')";

        // Call setData method from InsertUpdateDelete class to execute the query
        InsertUpdateDelete.setData(query, "Data inserted successfully");
        
        observer.updateTask();
        jTextField12.requestFocusInWindow();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        prepareNextEntry();
        jButton3.setVisible(false);
        jButton4.setVisible(true);
        jTextField12.requestFocusInWindow();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String taskID = getTaskID();
        String taskType = getTaskType();
        String importance = getImportance();
        String incharge = getIncharge();
        String note = getNote();
        String description = getDescription();
        
        TaskHistory taskHistory = new TaskHistory(taskID, taskType, importance,incharge, note, description);
        taskHistory.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(thirdColor);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseExited

    private void prepareNextEntry(){
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField19.setText("");        
    }
    
    // Declare nameToIdMap as a class member
    private Map<String, Integer> nameToIdMap = new HashMap<>();
    
    private void populateTaskTypeComboBox() {
        String query = "SELECT TaskTypeID, TaskType FROM TaskTypeT";
        ResultSet rs = Select.getData(query);

        try {
            while (rs.next()) {
                String taskType = rs.getString("TaskType");
                jComboBox2.addItem(taskType); // Add broker name to JComboBox
                // Assuming brokerId is retrieved from the ResultSet
                int taskTypeID = rs.getInt("TaskTypeID");
                // Add mapping between name and ID to the map
                nameToIdMap.put(taskType, taskTypeID);
                
                if (taskTypeID == 1) {
                jComboBox2.setSelectedItem(taskType); // Set the default value in the JComboBox
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void populateImportanceComboBox() {
        String query = "SELECT ImportanceID, Importance FROM importancet";
        ResultSet rs = Select.getData(query);

        try {
            while (rs.next()) {
                String importance = rs.getString("Importance");
                jComboBox3.addItem(importance); // Add broker name to JComboBox
                // Assuming brokerId is retrieved from the ResultSet
                int importanceID = rs.getInt("ImportanceID");
                // Add mapping between name and ID to the map
                nameToIdMap.put(importance, importanceID);
                
                if (importanceID == 1) {
                jComboBox3.setSelectedItem(importance); // Set the default value in the JComboBox
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void populateInchargeComboBox() {
        String query = "SELECT InchargeID, InchargeName FROM Incharget";
        ResultSet rs = Select.getData(query);

        try {
            while (rs.next()) {
                String inchargeName = rs.getString("InchargeName");
                jComboBox4.addItem(inchargeName); // Add broker name to JComboBox
                // Assuming brokerId is retrieved from the ResultSet
                int inchargeID = rs.getInt("InchargeID");
                // Add mapping between name and ID to the map
                nameToIdMap.put(inchargeName, inchargeID);
                
                if (inchargeID == 1) {
                jComboBox4.setSelectedItem(inchargeName); // Set the default value in the JComboBox
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void updateFields(int taskID, String dateCreated, String taskType, String description,String importance, String dateDue, String dateCompleted, String inchargeName, String note, boolean isActive) {
        // Update the fields with the new values
        prepareNextEntry();
        jComboBox2.setSelectedItem(taskType);
        jComboBox3.setSelectedItem(importance);
        jComboBox4.setSelectedItem(inchargeName);
        jCheckBox1.setSelected(isActive);
        
        jTextField11.setText(String.valueOf(taskID));
        jTextField12.setText(description);
        jTextField13.setText(dateCreated);
        jTextField14.setText(dateDue);
        jTextField15.setText(dateCompleted);
        jTextField19.setText(note);
    }
    
    public static TaskInsert getInstance(int taskID, String dateCreated, String taskType, String description,String importance, String dateDue, String dateCompleted, String inchargeName, String note, boolean isActive) {
        if (instance == null) {
            instance = new TaskInsert(taskID, dateCreated, taskType, description, importance, dateDue, dateCompleted, inchargeName, note, isActive);
        } else {            
            // If an instance already exists, update its fields with new data
            instance.updateFields(taskID, dateCreated, taskType, description, importance, dateDue, dateCompleted, inchargeName, note, isActive);
        }
        return instance;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (TaskInsert.instance != null) {
                TaskInsert.instance.dispose();
                }
                TaskInsert.instance = TaskInsert.getInstance(taskID, dateCreated, taskType, description, importance, dateDue, dateCompleted, inchargeName, note, isActive);
                TaskInsert.instance.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField19;
    // End of variables declaration//GEN-END:variables
}
